### ISSUE TITLE
Sync update DB option may be failing on empty database

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#116] opened 2020-03-18 17:31 UTC
**Describe the bug**
There is sql error, during run ./sync --updatedb on clear database for 006_meta.sql

**To Reproduce**
1. Clear database
2. Run ./sync --updatedb

**Expected behavior**
Fulfilled database structure.

**Screenshots**
![updatedb-bug](https://user-images.githubusercontent.com/313477/76989391-4e014a00-6957-11ea-97e6-9c590569f351.PNG)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.05

**Comment by mikegioia** [comment] 2020-03-21 21:43
@netandreus I can't reproduce this one. I tried on a clean database and with a newly cloned repo. Do you happen to have any more info here? Like what version of MySQL you're using etc. The fix you sent looks to be no different than this, just that the INSERT statement is in a separate file.

**Comment by netandreus** [comment] 2020-03-23 07:43
Ok, I will reproduce this case this evening collecting all logs and write here.

**Comment by mikegioia** [comment] 2020-03-23 12:41
I forgot to update this issue, sorry @netandreus. I merged this branch in over the weekend, and it should be in master now!

**Closed by mikegioia** 2020-03-23 12:41 UTC
Labels: needs info
