### ISSUE TITLE
Watcher

### ISSUE THREAD

**Issue by netandreus** [mikegioia/libremail#110] opened 2020-03-12 10:23 UTC
**Describe**
The goal of this issue is to make watcher daemon, which will be manage persistant connections to all imap servers and monitor it for 'mail' / 'update' / 'purge' events. When event occurs - watcher should run sync process for this mail account.

**mail event**
Should run sync process only for inbox folder of target mail account.

**update event**
Should run sync process for all folders of target mail account.

**purge event**
Should run sync process for all folders of target mail account.

**Comment by mikegioia** [comment] 2020-03-12 12:53
Thank you @netandreus do you mind keeping this issue and branch in your fork until the PR is ready to submit to this repo?

**Comment by netandreus** [comment] 2020-03-12 13:11
@mikegioia, of course. This is exactly what I'm doing right now. Current work for this issue will be here:
https://github.com/netandreus/libremail/tree/watcher
Comments are welcome :)

**Comment by mikegioia** [comment] 2020-03-15 17:52
FYI @netandreus I'm closing this issue here in this upstream repo, in lieu of keeping everything in your downstream repo. If you don't mind, I don't want to track anything as an issue that's not a bug or that's not in my current roadmap :D

**Closed by mikegioia** 2020-03-15 17:52 UTC

**Comment by netandreus** [comment] 2020-03-16 13:01
No problem, @mikegioia
